# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7

install:
  - echo "nothing to install"

# command to run tests, e.g. python setup.py test
script:
  - make test
