# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install codecov

# command to run tests, e.g. python setup.py test
script:
  - make coverage

after_success:
  - codecov
