# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

install:
  - pip3 install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - make test
